//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XOG.AppCode.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdSenseAd
    {
        public short Id { get; set; }
        public string Page { get; set; }
        public string Position { get; set; }
        public byte SortOrder { get; set; }
        public System.DateTime ValidTill { get; set; }
        public string AdLink { get; set; }
        public string ImageUrl { get; set; }
        public long ViewCount { get; set; }
        public string UpdatedByUserId { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
