//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XOG.AppCode.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoriesImage
    {
        public short Id { get; set; }
        public short CategoryId { get; set; }
        public string ImageUrl { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
