//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XOG.AppCode.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryTiming
    {
        public short Id { get; set; }
        public byte DayId { get; set; }
        public short FromHours { get; set; }
        public short FromMinutes { get; set; }
        public short ToHours { get; set; }
        public short ToMinutes { get; set; }
        public bool IsActive { get; set; }
    
        public virtual WeekDayStatus WeekDayStatus { get; set; }
    }
}
