//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XOG.AppCode.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfferBanner
    {
        public short Id { get; set; }
        public long OfferId { get; set; }
        public string DisplayName { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Enabled { get; set; }
        public string BannerImageUrl { get; set; }
        public string OfferUrl { get; set; }
        public byte Placement { get; set; }
    
        public virtual Offer Offer { get; set; }
    }
}
