//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XOG.AppCode.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfferDetail
    {
        public long Id { get; set; }
        public long OfferId { get; set; }
        public long ProductId { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Offer Offer { get; set; }
    }
}
