//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XOG.AppCode.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductVariant
    {
        public long Id { get; set; }
        public long ProductId { get; set; }
        public double Mrp { get; set; }
        public short Measure { get; set; }
        public string Volume { get; set; }
        public long StocksAvailable { get; set; }
        public short Gst { get; set; }
        public double Cost { get; set; }
        public double DiscountPercentage { get; set; }
        public bool Enabled { get; set; }
        public int MaxPurchase { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
