//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XOG.AppCode.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PushNotification
    {
        public long NotificationToken { get; set; }
        public long NotificationId { get; set; }
        public bool IsBackground { get; set; }
        public bool IsForeground { get; set; }
        public bool IsNotified { get; set; }
        public bool IsViewed { get; set; }
    
        public virtual AspNetUserNotificationToken AspNetUserNotificationToken { get; set; }
        public virtual Notification Notification { get; set; }
    }
}
