//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XOG.AppCode.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RedeemRequest
    {
        public long Id { get; set; }
        public long BankAccountId { get; set; }
        public double Amount { get; set; }
        public byte RequestState { get; set; }
        public System.DateTime RequestDateTime { get; set; }
        public Nullable<System.DateTime> RequestCompletionDateTime { get; set; }
    
        public virtual BankAccount BankAccount { get; set; }
    }
}
