//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XOG.AppCode.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReturnOrderDetail
    {
        public long Id { get; set; }
        public long ReturnOrderId { get; set; }
        public long OrderDetailsId { get; set; }
        public int Quantity { get; set; }
        public bool IsCancelled { get; set; }
    
        public virtual OrderDetail OrderDetail { get; set; }
        public virtual ReturnOrder ReturnOrder { get; set; }
    }
}
