//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XOG.AppCode.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserWalletListVW
    {
        public long Id { get; set; }
        public string UserId { get; set; }
        public string TransactionType { get; set; }
        public string OrderAction { get; set; }
        public long TransactionId { get; set; }
        public byte[] TimeStamp { get; set; }
        public Nullable<long> ActionId { get; set; }
        public Nullable<double> Amount { get; set; }
    }
}
