//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XOG.AppCode.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersWalletVW
    {
        public string WalletOfUserId { get; set; }
        public Nullable<int> TotalCredited { get; set; }
        public Nullable<int> TotalDebited { get; set; }
        public Nullable<double> Amount { get; set; }
    }
}
